apiVersion: v1
kind: Service
metadata:
  name: actor
  labels:
    serviceName: actor
    type: app
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    serviceName: actor
    type: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: actor
  labels:
    serviceName: actor
    type: app
spec:
  replicas: 1
  selector:
    matchLabels:
      serviceName: actor
      type: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: actor
      labels:
        serviceName: actor
        stack: go
        type: app
    spec:
      containers:
      - env:
        - name: GIN_MODE
          value: debug
        - name: DATABASE_ADDRESS
          value: postgres-actor:5432
        - name: DATABASE_USERNAME
          value: actor
        - name: DATABASE_PASSWORD
          value: actor
        - name: DATABASE_NAME
          value: actor
        - name: DATABASE_LOG
          value: 'true'
        - name: DATABASE_MAX_OPEN
          value: '25'
        - name: DATABASE_MAX_IDLE
          value: '2'
        - name: KONG_ADMIN_URL
          value: http://kong:8001
        - name: KONG_AUTH_URL
          value: https://auth.shajaro.com
        - name: PROVISION_KEY
          value: RRHTRkHLf4ZRQx0ucfBQ49zAmGv30UeG
        name: actor
        image: gcr.io/solid-terra-207000/actor:develop
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 30
          tcpSocket:
            port: http
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 30
          httpGet:
            path: /v1/healthz
            port: http
      terminationGracePeriodSeconds: 30