apiVersion: v1
kind: Service
metadata:
  name: cassandra-kong
  labels:
    serviceName: kong
    type: datastore
    datastoreName: cassandra
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  ports:
    - name: cql
      port: 9042
      protocol: TCP
      targetPort: 9042
  selector:
    serviceName: kong
    type: datastore
    datastoreName: cassandra
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: cassandra-kong
  labels:
    datastoreName: cassandra
    serviceName: kong
    type: datastore
spec:
  serviceName: cassandra-kong
  updateStrategy:
      type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      datastoreName: cassandra
      serviceName: kong
      type: datastore
  template:
    metadata:
      name: cassandra-kong
      labels:
        datastoreName: cassandra
        serviceName: kong
        type: datastore
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: cassandra-kong
        image: cassandra:3.11.2
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
          protocol: TCP
        - containerPort: 7001
          name: tls-intra-node
          protocol: TCP
        - containerPort: 7199
          name: jmx
          protocol: TCP
        - containerPort: 9042
          name: cql
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 128M
          - name: CASSANDRA_SEEDS
          # <pod_name>.<svc-name>.<namespace>.svc.cluster.local
            value: cassandra-kong-0.cassandra-kong.$(POD_NAMESPACE).svc.cluster.local
          - name: CASSANDRA_CLUSTER_NAME
            value: "kong-cs"
          - name: CASSANDRA_DC
            value: "kong-dc"
          - name: CASSANDRA_RACK
            value: "kong-rack"
          - name: CASSANDRA_AUTO_BOOTSTRAP
            value: "false"
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        readinessProbe:
          failureThreshold: 6
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9042
        # These volume mounts are persistent. They are like inline claims,
        # but not exactly because the names need to match exactly one of
        # the stateful pod volumes.
        livenessProbe:
          failureThreshold: 6
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9042
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: "/var/lib/cassandra/data"
          name: data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  # do not use these in production until ssd GCEPersistentDisk or other ssd pd
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi