apiVersion: v1
kind: Service
metadata:
  name: kong
  labels:
    serviceName: kong
    role: internal
spec:
  type: ClusterIP
  ports:
  - name: consumer
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    serviceName: kong
    type: app
---
apiVersion: v1
kind: Service
metadata:
  name: kong-ext
  labels:
    serviceName: kong
    role: external
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    serviceName: kong
    type: app
---
apiVersion: v1
kind: Service
metadata:
  name: kongdash
  labels:
    serviceName: kongdash
    role: external
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    serviceName: kongdash
    type: app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
  name: kong
  labels:
    serviceName: kong
    role: external
spec:
  tls:
  - secretName: auth-ssl
  rules:
  - host: api.dynastymasra.me
    http:
      paths:
      - backend:
         serviceName: kong-ext
         servicePort: http
  - host: auth.dynastymasra.me
    http:
      paths:
      - backend:
         serviceName: kong-ext
         servicePort: http
  - host: kong.dynastymasra.me
    http:
      paths:
      - backend:
          serviceName: kongdash
          servicePort: http